import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { ChangeEvent, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [email, setEmail] = useState("");
  const [numberOfEmails, setNumberOfEmails] = useState("");

  const fireAwayEmails = () => {
    
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"flex flex-col justify-start items-center min-h-screen"}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        <form onSubmit={fireAwayEmails}>
        <div className={"flex flex-row justify-center items-start mt-32"}>
          
          <div className='flex flex-col p-1'>
            <p className='text-gray-300 font-semibold text-lg'>Email Address:</p>
            <input className='rounded-md h-10 w-96 bg-gray-600' value={email} onChange={(e: ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)}></input>
          </div>
          <div className='flex flex-col p-1'>
            <p className='text-gray-300 font-semibold text-lg'>No. of Emails</p>
            <input className='rounded-md h-10 w-20 bg-gray-600' value={numberOfEmails} onChange={(e: ChangeEvent<HTMLInputElement>) => setNumberOfEmails(e.target.value)}></input>
          </div>
          
        </div>
        </form>
        <input type="submit" value="Shoot" className='bg-blue-800 w-64 h-10 rounded-lg mt-5'></input>
      </main>
    </>
  )
}
