import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { ChangeEvent, useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [email, setEmail] = useState("");
  const [numberOfEmails, setNumberOfEmails] = useState("");
  const [submissionInProgress, setSubmissionInProgress] = useState(false);
  const [emailsSentMessage, setEmailsSentMessage] = useState("");

  const fireAwayEmails = async (e: any) => {
    setEmailsSentMessage("");
    e.preventDefault();
    setSubmissionInProgress(true);
    const emails_response = await axios.post("/api/sendEmails", { to_email_address: email, no_of_emails: numberOfEmails });
    console.log(emails_response);
    setSubmissionInProgress(false);
    setEmailsSentMessage("Emails Sent");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"flex flex-col justify-start items-center min-h-screen"}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        <form onSubmit={fireAwayEmails}>
        <div className={"flex flex-row justify-center items-start mt-32"}>
          
          <div className='flex flex-col p-1'>
            <p className='text-gray-300 font-semibold text-lg'>Email Address:</p>
            <input className='rounded-md h-10 w-96 bg-gray-600 px-1' type={'email'} required={true} value={email} onChange={(e: ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)}></input>
          </div>
          <div className='flex flex-col p-1'>
            <p className='text-gray-300 font-semibold text-lg'>No. of Emails</p>
            <input className='rounded-md h-10 w-20 bg-gray-600 px-1' type={'number'} required={true} value={numberOfEmails} onChange={(e: ChangeEvent<HTMLInputElement>) => setNumberOfEmails(e.target.value)}></input>
          </div>
          
        </div>
        <button type="submit" value="Shoot" className='bg-blue-800 w-64 h-10 rounded-lg mt-5 disabled:bg-blue-300' disabled={submissionInProgress}>Shoot</button>
        <p className='text-blue-800 font-semibold mt-2'>{emailsSentMessage}</p>
        </form>
      </main>
    </>
  )
}
